name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Uruchamiaj codziennie o północy
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: MikolajZabawa  # Twoja nazwa użytkownika GitHub
          outputs: dist/snake.svg

      - name: Push Snake Animation to the Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
