name: GitHub Contributions Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Codziennie o północy
  push:
    branches:
      - main  # Upewnij się, że to jest główna gałąź w Twoim repozytorium

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Updating package list..."
          sudo apt-get update
          echo "Installing dependencies..."
          sudo apt-get install -y python3-pip python3-dev
          python3 -m pip install --upgrade pip
          echo "Dependencies installed."

      - name: Install github-contribution-grid-snake from GitHub
        run: |
          echo "Installing github-contribution-grid-snake..."
          pip install git+https://github.com/salesp07/github-contribution-grid-snake.git
          echo "github-contribution-grid-snake installed successfully."

      - name: Generate Snake SVG
        run: |
          echo "Generating Snake SVG..."
          github-contribution-grid-snake -u MikolajZabawa -o ./output/github-contribution-grid-snake.svg
          echo "SVG generated successfully."

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: ./output/github-contribution-grid-snake.svg
