name: GitHub Contributions Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Codziennie o północy
  push:
    branches:
      - main  # Upewnij się, że to jest główna gałąź w Twoim repozytorium

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Jeśli masz jakiś dodatkowy plik requirements.txt, inaczej pomiń to

      - name: Download GitHub Contributions Snake
        run: |
          curl -L https://github.com/salesp07/github-contribution-grid-snake/releases/download/v1.0.0/github-contribution-grid-snake-linux-x86_64.tar.gz -o github-contribution-grid-snake.tar.gz
          tar -xzf github-contribution-grid-snake.tar.gz
          chmod +x github-contribution-grid-snake
          
      - name: Generate Snake SVG
        run: |
          ./github-contribution-grid-snake -u MikolajZabawa -o ./output/github-contribution-grid-snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: ./output/github-contribution-grid-snake.svg
