name: GitHub Contributions Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Codziennie o północy
  push:
    branches:
      - main  # Upewnij się, że to jest główna gałąź w Twoim repozytorium

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install github-contributions-snake

      - name: Generate Snake SVG
        run: |
          github-contributions-snake -u MikolajZabawa -o ./output/github-contribution-grid-snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: ./output/github-contribution-grid-snake.svg
